# Generated by Django 4.1.3 on 2023-02-23 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
