# Generated by Django 4.1.7 on 2023-02-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_delete_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(choices=[('Bodybuilding', 'BodyBuilding'), ('Running', 'Running'), ('Sports', 'Sports'), ('Fitness', 'Fitness'), ('Wellbeing', 'Wellbeing'), ('Strength Training', 'Strength Training'), ('Hypertrophy', 'Hypertrophy'), ('CrossFit', 'CrossFit')], default='Fitness', max_length=30),
        ),
    ]
