# Generated by Django 4.1.7 on 2023-03-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_new_rkuynm', upload_to='images/'),
        ),
    ]
