# Generated by Django 4.1.7 on 2023-03-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(choices=[('Bodybuilding', 'BodyBuilding'), ('Running', 'Running'), ('Sports', 'Sports'), ('Fitness', 'Fitness'), ('Wellbeing', 'Wellbeing'), ('Strength Training', 'Strength Training'), ('Hypertrophy', 'Hypertrophy'), ('CrossFit', 'CrossFit')], max_length=30),
        ),
    ]
